### PR TITLE
Fix #532 by sorting table keys when processing content

### LINKED ISSUE #532: Content re-ordered
I've had a freaky problem come up in multiple projects now where _some_ rendering passes will miss-order content. Anything that is wrapped in some markup (font style or weight change, etc.) can get pushed to the end of the line it's supposed to be in. Usually running another rendering pass clears this up. It's not consistent on whether the first pass or the second or the third or whatever will fail like this.

Compare the order of italicized bits:

selection_046

With the source:

```TeX
...
\footnote{Smarto, \em{Pursued}, 122.}
...
\footnote{Anthony A. Hoekema, \em{Saved by Grace} (Grand Rapids, MI: Eerdmans, 1989), 178.}
...
```
Note the `\em{}` tagged content is typeset out of sequence.

### PR DESCRIPTION
**Pull request by simoncozens**
* This could do with a test.
* I tried to find other examples where we are using pairs() on AST content, but didn't see any. A review would be helpful.

### CODE REVIEW

**Comment by alerque** [comment]
This fixes #972, but not #532. Its likely the same problem but since it doesn't uses inputfilter there is another case somewhere. I'm trying to track it down.

**Comment by alerque** [comment]
I take back what I said, this does seem to fix #532. The project in question there has an elaborate work around for #355 that basically pre-processes everything with input filter fixing potential hyphenation issues at apostrophes. That does explain why it turned up regularly in a few projects and never in others.

As for tests ... I'm not to confident we have a way to reliably test non-determinism. The most likely candidate would be a Busted test unit that iterated over something a bunch of times and make sure it was the same every time. Hmmmm, yes let me try that....

File: core/utilities.lua [hunk 1]
```diff
@@ -125,6 +125,22 @@ utilities.map = function (func, array)
...
+utilities.sortedpairs = function (input)
+  local keys = {}
+  for k, _ in pairs(input) do
+    keys[#keys+1] = k
+  end
+  table.sort(keys, function(a, b)
+    if type(a) ~= type(b) then return false end
+    return a < b
+  end)
+  return coroutine.wrap(function()
```
Comment (alerque) [inline core/utilities.lua:137]: Clever and works, but I'm curious why you reached for coroutines instead of the classic Lua idiom of keeping an iteration counter outside the function.

Comment (simoncozens) [reply core/utilities.lua:137]: Well, pairs() is an iterator, and we need our own version - I just thought coroutines were[ the way you do iterators](https://www.lua.org/pil/9.3.html) in Lua. :-) (Turns out you can do it by returning a generator function as well, but truth to tell I just grabbed the structure from `utilities.gtoke`)

Comment (alerque) [reply core/utilities.lua:137]: Fair enough.

**Comment by alerque** [comment]
I haven't come up a test that fails using `pairs()` yet.

Here'se what tried (plain in `spec/utilities_spec.lua` and run with `busted -t utilities`):

```lua
SILE = require("core/sile")

describe("The #utilities library ", function()
  it("should have a short alias", function() assert.is.truthy(SU == SILE.utilities) end)

  describe("sortedpairs() function", function()
    local input = { "a", _ = true, "c", "b", foo = "bar", "E" }
    it("avoid Lua’s non-determinism", function ()
      local testit = function ()
        for _ = 1, 100 do
          local i = 1
          -- for k, v in SU.sortedpairs(input) do
          for k, v in pairs(input) do
            if k == 1 and v ~= "a" then return false
            elseif k == 2 and v ~= "c" then return false
            elseif k == 3 and v ~= "b" then return false
            elseif k == 4 and v ~= "E" then return false
            elseif k == "_" and v ~= true then return false
            elseif k == "foo" and v ~= "bar" then return false
            end
            i = i + 1
          end
        end
        return true
      end
      assert.is.truthy(testit())
    end)
  end)

end)
```

**Comment by alerque** [comment]
So I've still completely failed to create a test that reproduces the problem. It's hard to test that you're doing it right when you can't get a test you know in wrong to reliably fail as a starting point.

However I did some digging and came up with a few more instances of `pairs()` that either are or could be problematic. Some of them likely don't matter but technically were out of whack (defining hyphenation definition patterns in order, applying them randomly) others could clearly have tripped us up without warning (`outputYourself()` iterating nodes out of order).

For reference if this comes up again, I found these by first adding a wrapper to `pairs()`:

```lua
debugpairs = function (var)
  if var[1] then
    utilities.error("called pairs() on what looks like a sequential table")
  end
  return pairs(var)
end
```

Then aggressively replaced our use of `pairs()` with `debugpairs()`:

    $ git ls-files '*.lua' | xargs -n1 sed -i -e 's/in pairs/in debugpairs/g'

Then I‌ worked through running tests & building the manual replacing the bad lines with `ipairs()` or `SU.sortedpairs()` as appropriate until it stopped dying.

**Comment by alerque** [comment]
In retrospect we could/should probably have just used `pl.tablex.sort()` for this. :man_shrugging:

**Comment by alerque** [comment]
One I wasn't sure about and you may recognize @simoncozens:

https://github.com/sile-typesetter/sile/blob/175baad18d6f2b1591d2d941c346e7f7ba8b293c/lua-libraries/lomwithpos.lua#L42

Unfortunately this option doesn't seem to be getting tested at all because replacing `pairs()` here with `foo()` doesn't fail our tests at all.
