### PR TITLE
fix(core): _drawString should take an offset

### LINKED ISSUE #1078: new version don`t work good in Arabic
image
this is test/sura-2.sil

### PR DESCRIPTION
**Pull request by simoncozens**
Fixes #1078

### CODE REVIEW

File: core/libtexpdf-output.lua [hunk 1]
```diff
@@ -109,9 +109,9 @@ SILE.outputters.libtexpdf = {
     return self:drawHbox(value, width)
   end,
 
-  _drawString = function(self, str, width)
+  _drawString = function(self, str, width, x_offset, y_offset)
     local x, y = self:getCursor()
-    pdf.setstring(x, y, str, string.len(str), self._font, width)
+    pdf.setstring(x+x_offset, y+y_offset, str, string.len(str), self._font, width)
```
Comment (alerque) [inline core/libtexpdf-output.lua:114]: This will take care of the libtexpdf's internal comprehension of where the cursor is, but I think we need a call to self:setCursor() here to match our own internal comprehension of the same, otherwise they are going to be out of sync.

**Review by alerque — CHANGES_REQUESTED** [review]

File: core/libtexpdf-output.lua (hunk 1 above)
Comment (alerque) [reply core/libtexpdf-output.lua:114]: Or maybe I'm still misunderstanding this. I'm surprised it passed the BBT-RTL test for rules.

Comment (simoncozens) [reply core/libtexpdf-output.lua:114]: No! Offsets should not affect the cursor; that is the whole point of offsets.

Comment (simoncozens) [reply core/libtexpdf-output.lua:114]: ( https://simoncozens.github.io/fonts-and-layout//concepts.html#advance-and-positioning )

Comment (alerque) [reply core/libtexpdf-output.lua:114]: Oh crikey. The rules test no longer mixes text strings & rules....

Comment (simoncozens) [reply core/libtexpdf-output.lua:114]: The offsets should only non-zero when Harfbuzz gives us positioning information to draw a glyph at a certain displacement (e.g. mark positioning, cursive positioning). Any other time it should behave as before.

**Review by alerque — APPROVED** [review]
